---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: marcpar/floki-api:latest
        ports:
        - containerPort: 4002
        env:
        - name: PORT
          value: "4002"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database-name
        - name: DBHOST
          value: "db"
        - name: DBPORT
          value: "5432"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"